import { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Sign In',
    description: 'Generated by create next app',
}

export default function SignInLayout({
    children, // will be a page or nested layout
}: {
    children: React.ReactNode
}) {
    return (
        <section>
            {children}
        </section>
    )
}